/**
 * Auto-generated by scripts/build-vault-index.mjs
 * Do not edit manually.
 */
export const vaultIndexRaw = [
  {
    "slug": "_Index_of_biblioteca",
    "raw": "%% Zoottelkeeper: Beginning of the autogenerated index file list  %%\r\n[[canonico/m01|M01 — Mandato Normativo]]\r\n[[canonico/m02|M02 — Ciclo Virtuoso]]\r\n[[canonico/m03|M03 — Estándares Internacionales]]\r\n[[canonico/m04|M04 — JTBD Comunidad]]\r\n[[canonico/m05|M05 — BMK Procesos Misionales]]\r\n[[canonico/m06|M06 — BMK Créditos CCA]]\r\n[[canonico/m07|M07 — 21 BPA]]\r\n[[canonico/m08|M08 — (DRAFT)]]\r\n[[canonico/m09|M09 — (DRAFT)]]\r\n[[canonico/m10|M10 — (DRAFT)]]\r\n[[canonico/m11|M11 — (DRAFT)]]\r\n[[canonico/m12|M12 — (DRAFT)]]\r\n%% Zoottelkeeper: End of the autogenerated index file list  %%\r\n"
  }
] as const;
