/**
 * Auto-generated by scripts/build-vault-index.mjs (v8g-l5.1)
 * Do not edit manually.
 */
export interface VaultTreeNode {
  type: 'folder' | 'file';
  id: string;
  name: string;
  slug: string;
  href?: string;
  children: VaultTreeNode[];
}

export const vaultTreeRoot: VaultTreeNode[] = [
  {
    "type": "folder",
    "id": "acuerdos",
    "name": "acuerdos",
    "slug": "acuerdos",
    "children": [
      {
        "type": "file",
        "id": "acuerdos/ea-001.mdx",
        "name": "ea-001",
        "slug": "acuerdos/ea-001",
        "href": "/acuerdos/ea-001",
        "children": []
      }
    ]
  },
  {
    "type": "folder",
    "id": "biblio",
    "name": "biblio",
    "slug": "biblio",
    "children": [
      {
        "type": "file",
        "id": "biblio/abet2024criteria.md",
        "name": "abet2024criteria",
        "slug": "biblio/abet2024criteria",
        "href": "/biblio/abet2024criteria",
        "children": []
      },
      {
        "type": "file",
        "id": "biblio/beer1979heart.md",
        "name": "beer1979heart",
        "slug": "biblio/beer1979heart",
        "href": "/biblio/beer1979heart",
        "children": []
      },
      {
        "type": "file",
        "id": "biblio/beneitone2007tuning.md",
        "name": "beneitone2007tuning",
        "slug": "biblio/beneitone2007tuning",
        "href": "/biblio/beneitone2007tuning",
        "children": []
      },
      {
        "type": "file",
        "id": "biblio/carayannis2006mode3.md",
        "name": "carayannis2006mode3",
        "slug": "biblio/carayannis2006mode3",
        "href": "/biblio/carayannis2006mode3",
        "children": []
      },
      {
        "type": "file",
        "id": "biblio/carayannis2012quintuple.md",
        "name": "carayannis2012quintuple",
        "slug": "biblio/carayannis2012quintuple",
        "href": "/biblio/carayannis2012quintuple",
        "children": []
      },
      {
        "type": "file",
        "id": "biblio/cast2024udl3.md",
        "name": "cast2024udl3",
        "slug": "biblio/cast2024udl3",
        "href": "/biblio/cast2024udl3",
        "children": []
      },
      {
        "type": "file",
        "id": "biblio/chapman2000crispdm.md",
        "name": "chapman2000crispdm",
        "slug": "biblio/chapman2000crispdm",
        "href": "/biblio/chapman2000crispdm",
        "children": []
      },
      {
        "type": "file",
        "id": "biblio/christensen2016competing.md",
        "name": "christensen2016competing",
        "slug": "biblio/christensen2016competing",
        "href": "/biblio/christensen2016competing",
        "children": []
      },
      {
        "type": "file",
        "id": "biblio/clark1998entrepreneurial.md",
        "name": "clark1998entrepreneurial",
        "slug": "biblio/clark1998entrepreneurial",
        "href": "/biblio/clark1998entrepreneurial",
        "children": []
      },
      {
        "type": "file",
        "id": "biblio/colombia1992ley30.md",
        "name": "colombia1992ley30",
        "slug": "biblio/colombia1992ley30",
        "href": "/biblio/colombia1992ley30",
        "children": []
      },
      {
        "type": "file",
        "id": "biblio/compagnucci2020thirdmission.md",
        "name": "compagnucci2020thirdmission",
        "slug": "biblio/compagnucci2020thirdmission",
        "href": "/biblio/compagnucci2020thirdmission",
        "children": []
      },
      {
        "type": "file",
        "id": "biblio/conpes2018crecverde.md",
        "name": "conpes2018crecverde",
        "slug": "biblio/conpes2018crecverde",
        "href": "/biblio/conpes2018crecverde",
        "children": []
      },
      {
        "type": "file",
        "id": "biblio/conpes2021cti.md",
        "name": "conpes2021cti",
        "slug": "biblio/conpes2021cti",
        "href": "/biblio/conpes2021cti",
        "children": []
      },
      {
        "type": "file",
        "id": "biblio/crawley2014cdio.md",
        "name": "crawley2014cdio",
        "slug": "biblio/crawley2014cdio",
        "href": "/biblio/crawley2014cdio",
        "children": []
      },
      {
        "type": "file",
        "id": "biblio/gac2022rbm.md",
        "name": "gac2022rbm",
        "slug": "biblio/gac2022rbm",
        "href": "/biblio/gac2022rbm",
        "children": []
      },
      {
        "type": "file",
        "id": "biblio/geels2002mlp.md",
        "name": "geels2002mlp",
        "slug": "biblio/geels2002mlp",
        "href": "/biblio/geels2002mlp",
        "children": []
      },
      {
        "type": "file",
        "id": "biblio/gibbons1994newproduction.md",
        "name": "gibbons1994newproduction",
        "slug": "biblio/gibbons1994newproduction",
        "href": "/biblio/gibbons1994newproduction",
        "children": []
      },
      {
        "type": "file",
        "id": "biblio/iso2018eoms.md",
        "name": "iso2018eoms",
        "slug": "biblio/iso2018eoms",
        "href": "/biblio/iso2018eoms",
        "children": []
      },
      {
        "type": "file",
        "id": "biblio/kaplan2004strategymaps.md",
        "name": "kaplan2004strategymaps",
        "slug": "biblio/kaplan2004strategymaps",
        "href": "/biblio/kaplan2004strategymaps",
        "children": []
      },
      {
        "type": "file",
        "id": "biblio/kaplananderson2004tdabc.md",
        "name": "kaplananderson2004tdabc",
        "slug": "biblio/kaplananderson2004tdabc",
        "href": "/biblio/kaplananderson2004tdabc",
        "children": []
      },
      {
        "type": "file",
        "id": "biblio/maderasepulveda2026bmk001.md",
        "name": "maderasepulveda2026bmk001",
        "slug": "biblio/maderasepulveda2026bmk001",
        "href": "/biblio/maderasepulveda2026bmk001",
        "children": []
      },
      {
        "type": "file",
        "id": "biblio/maderasepulveda2026bmk002.md",
        "name": "maderasepulveda2026bmk002",
        "slug": "biblio/maderasepulveda2026bmk002",
        "href": "/biblio/maderasepulveda2026bmk002",
        "children": []
      },
      {
        "type": "file",
        "id": "biblio/markard2012transitions.md",
        "name": "markard2012transitions",
        "slug": "biblio/markard2012transitions",
        "href": "/biblio/markard2012transitions",
        "children": []
      },
      {
        "type": "file",
        "id": "biblio/minciencias2022piiom.md",
        "name": "minciencias2022piiom",
        "slug": "biblio/minciencias2022piiom",
        "href": "/biblio/minciencias2022piiom",
        "children": []
      },
      {
        "type": "file",
        "id": "biblio/niven2003bscgov.md",
        "name": "niven2003bscgov",
        "slug": "biblio/niven2003bscgov",
        "href": "/biblio/niven2003bscgov",
        "children": []
      },
      {
        "type": "file",
        "id": "biblio/nonaka1995knowledgecreating.md",
        "name": "nonaka1995knowledgecreating",
        "slug": "biblio/nonaka1995knowledgecreating",
        "href": "/biblio/nonaka1995knowledgecreating",
        "children": []
      },
      {
        "type": "file",
        "id": "biblio/nowotny2003mode2revisited.md",
        "name": "nowotny2003mode2revisited",
        "slug": "biblio/nowotny2003mode2revisited",
        "href": "/biblio/nowotny2003mode2revisited",
        "children": []
      },
      {
        "type": "file",
        "id": "biblio/oecd2018learningcompass.md",
        "name": "oecd2018learningcompass",
        "slug": "biblio/oecd2018learningcompass",
        "href": "/biblio/oecd2018learningcompass",
        "children": []
      },
      {
        "type": "file",
        "id": "biblio/prahalad1990core.md",
        "name": "prahalad1990core",
        "slug": "biblio/prahalad1990core",
        "href": "/biblio/prahalad1990core",
        "children": []
      },
      {
        "type": "file",
        "id": "biblio/schot2018frame3.md",
        "name": "schot2018frame3",
        "slug": "biblio/schot2018frame3",
        "href": "/biblio/schot2018frame3",
        "children": []
      },
      {
        "type": "file",
        "id": "biblio/stokes1997pasteur.md",
        "name": "stokes1997pasteur",
        "slug": "biblio/stokes1997pasteur",
        "href": "/biblio/stokes1997pasteur",
        "children": []
      },
      {
        "type": "file",
        "id": "biblio/udfjc2025acu00425.md",
        "name": "udfjc2025acu00425",
        "slug": "biblio/udfjc2025acu00425",
        "href": "/biblio/udfjc2025acu00425",
        "children": []
      },
      {
        "type": "file",
        "id": "biblio/ulwick2016jtbd.md",
        "name": "ulwick2016jtbd",
        "slug": "biblio/ulwick2016jtbd",
        "href": "/biblio/ulwick2016jtbd",
        "children": []
      },
      {
        "type": "file",
        "id": "biblio/unesco2021reimagining.md",
        "name": "unesco2021reimagining",
        "slug": "biblio/unesco2021reimagining",
        "href": "/biblio/unesco2021reimagining",
        "children": []
      },
      {
        "type": "file",
        "id": "biblio/wenger1998cop.md",
        "name": "wenger1998cop",
        "slug": "biblio/wenger1998cop",
        "href": "/biblio/wenger1998cop",
        "children": []
      }
    ]
  },
  {
    "type": "folder",
    "id": "canonico",
    "name": "canonico",
    "slug": "canonico",
    "children": [
      {
        "type": "file",
        "id": "canonico/dash-canonico.md",
        "name": "dash-canonico",
        "slug": "canonico/dash-canonico",
        "href": "/canonico/dash-canonico",
        "children": []
      },
      {
        "type": "file",
        "id": "canonico/m01.mdx",
        "name": "m01",
        "slug": "canonico/m01",
        "href": "/canonico/m01",
        "children": []
      },
      {
        "type": "file",
        "id": "canonico/m02.mdx",
        "name": "m02",
        "slug": "canonico/m02",
        "href": "/canonico/m02",
        "children": []
      },
      {
        "type": "file",
        "id": "canonico/m03.mdx",
        "name": "m03",
        "slug": "canonico/m03",
        "href": "/canonico/m03",
        "children": []
      },
      {
        "type": "file",
        "id": "canonico/m04.mdx",
        "name": "m04",
        "slug": "canonico/m04",
        "href": "/canonico/m04",
        "children": []
      },
      {
        "type": "file",
        "id": "canonico/m05.mdx",
        "name": "m05",
        "slug": "canonico/m05",
        "href": "/canonico/m05",
        "children": []
      },
      {
        "type": "file",
        "id": "canonico/m06.mdx",
        "name": "m06",
        "slug": "canonico/m06",
        "href": "/canonico/m06",
        "children": []
      },
      {
        "type": "file",
        "id": "canonico/m07.mdx",
        "name": "m07",
        "slug": "canonico/m07",
        "href": "/canonico/m07",
        "children": []
      },
      {
        "type": "file",
        "id": "canonico/m08.mdx",
        "name": "m08",
        "slug": "canonico/m08",
        "href": "/canonico/m08",
        "children": []
      },
      {
        "type": "file",
        "id": "canonico/m09.mdx",
        "name": "m09",
        "slug": "canonico/m09",
        "href": "/canonico/m09",
        "children": []
      },
      {
        "type": "file",
        "id": "canonico/m10.mdx",
        "name": "m10",
        "slug": "canonico/m10",
        "href": "/canonico/m10",
        "children": []
      },
      {
        "type": "file",
        "id": "canonico/m11.mdx",
        "name": "m11",
        "slug": "canonico/m11",
        "href": "/canonico/m11",
        "children": []
      },
      {
        "type": "file",
        "id": "canonico/m12.mdx",
        "name": "m12",
        "slug": "canonico/m12",
        "href": "/canonico/m12",
        "children": []
      }
    ]
  },
  {
    "type": "folder",
    "id": "comunidades",
    "name": "comunidades",
    "slug": "comunidades",
    "children": [
      {
        "type": "folder",
        "id": "comunidades/extension",
        "name": "extension",
        "slug": "comunidades/extension",
        "children": [
          {
            "type": "folder",
            "id": "comunidades/extension/centros",
            "name": "centros",
            "slug": "comunidades/extension/centros",
            "children": [
              {
                "type": "folder",
                "id": "comunidades/extension/centros/ilud",
                "name": "ilud",
                "slug": "comunidades/extension/centros/ilud",
                "children": [
                  {
                    "type": "file",
                    "id": "comunidades/extension/centros/ilud/index.mdx",
                    "name": "index",
                    "slug": "comunidades/extension/centros/ilud/index",
                    "href": "/comunidades/extension/centros/ilud/index",
                    "children": []
                  }
                ]
              }
            ]
          },
          {
            "type": "file",
            "id": "comunidades/extension/index.mdx",
            "name": "index",
            "slug": "comunidades/extension/index",
            "href": "/comunidades/extension/index",
            "children": []
          }
        ]
      },
      {
        "type": "folder",
        "id": "comunidades/formacion",
        "name": "formacion",
        "slug": "comunidades/formacion",
        "children": [
          {
            "type": "folder",
            "id": "comunidades/formacion/escuelas",
            "name": "escuelas",
            "slug": "comunidades/formacion/escuelas",
            "children": [
              {
                "type": "folder",
                "id": "comunidades/formacion/escuelas/fisica",
                "name": "fisica",
                "slug": "comunidades/formacion/escuelas/fisica",
                "children": [
                  {
                    "type": "folder",
                    "id": "comunidades/formacion/escuelas/fisica/cabas",
                    "name": "cabas",
                    "slug": "comunidades/formacion/escuelas/fisica/cabas",
                    "children": [
                      {
                        "type": "folder",
                        "id": "comunidades/formacion/escuelas/fisica/cabas/magnetismo",
                        "name": "magnetismo",
                        "slug": "comunidades/formacion/escuelas/fisica/cabas/magnetismo",
                        "children": [
                          {
                            "type": "file",
                            "id": "comunidades/formacion/escuelas/fisica/cabas/magnetismo/evaluaciones-tipo.mdx",
                            "name": "evaluaciones-tipo",
                            "slug": "comunidades/formacion/escuelas/fisica/cabas/magnetismo/evaluaciones-tipo",
                            "href": "/comunidades/formacion/escuelas/fisica/cabas/magnetismo/evaluaciones-tipo",
                            "children": []
                          },
                          {
                            "type": "file",
                            "id": "comunidades/formacion/escuelas/fisica/cabas/magnetismo/index.mdx",
                            "name": "index",
                            "slug": "comunidades/formacion/escuelas/fisica/cabas/magnetismo/index",
                            "href": "/comunidades/formacion/escuelas/fisica/cabas/magnetismo/index",
                            "children": []
                          }
                        ]
                      }
                    ]
                  },
                  {
                    "type": "file",
                    "id": "comunidades/formacion/escuelas/fisica/index.mdx",
                    "name": "index",
                    "slug": "comunidades/formacion/escuelas/fisica/index",
                    "href": "/comunidades/formacion/escuelas/fisica/index",
                    "children": []
                  },
                  {
                    "type": "file",
                    "id": "comunidades/formacion/escuelas/fisica/principios-escuela-emprendedora.mdx",
                    "name": "principios-escuela-emprendedora",
                    "slug": "comunidades/formacion/escuelas/fisica/principios-escuela-emprendedora",
                    "href": "/comunidades/formacion/escuelas/fisica/principios-escuela-emprendedora",
                    "children": []
                  }
                ]
              }
            ]
          },
          {
            "type": "folder",
            "id": "comunidades/formacion/facultades",
            "name": "facultades",
            "slug": "comunidades/formacion/facultades",
            "children": [
              {
                "type": "folder",
                "id": "comunidades/formacion/facultades/ciencias-matematicas-y-naturales",
                "name": "ciencias-matematicas-y-naturales",
                "slug": "comunidades/formacion/facultades/ciencias-matematicas-y-naturales",
                "children": [
                  {
                    "type": "folder",
                    "id": "comunidades/formacion/facultades/ciencias-matematicas-y-naturales/programas",
                    "name": "programas",
                    "slug": "comunidades/formacion/facultades/ciencias-matematicas-y-naturales/programas",
                    "children": [
                      {
                        "type": "folder",
                        "id": "comunidades/formacion/facultades/ciencias-matematicas-y-naturales/programas/fisica",
                        "name": "fisica",
                        "slug": "comunidades/formacion/facultades/ciencias-matematicas-y-naturales/programas/fisica",
                        "children": [
                          {
                            "type": "file",
                            "id": "comunidades/formacion/facultades/ciencias-matematicas-y-naturales/programas/fisica/competencias-fci.mdx",
                            "name": "competencias-fci",
                            "slug": "comunidades/formacion/facultades/ciencias-matematicas-y-naturales/programas/fisica/competencias-fci",
                            "href": "/comunidades/formacion/facultades/ciencias-matematicas-y-naturales/programas/fisica/competencias-fci",
                            "children": []
                          },
                          {
                            "type": "file",
                            "id": "comunidades/formacion/facultades/ciencias-matematicas-y-naturales/programas/fisica/creditos-academicos-cca.mdx",
                            "name": "creditos-academicos-cca",
                            "slug": "comunidades/formacion/facultades/ciencias-matematicas-y-naturales/programas/fisica/creditos-academicos-cca",
                            "href": "/comunidades/formacion/facultades/ciencias-matematicas-y-naturales/programas/fisica/creditos-academicos-cca",
                            "children": []
                          },
                          {
                            "type": "file",
                            "id": "comunidades/formacion/facultades/ciencias-matematicas-y-naturales/programas/fisica/index.mdx",
                            "name": "index",
                            "slug": "comunidades/formacion/facultades/ciencias-matematicas-y-naturales/programas/fisica/index",
                            "href": "/comunidades/formacion/facultades/ciencias-matematicas-y-naturales/programas/fisica/index",
                            "children": []
                          }
                        ]
                      }
                    ]
                  },
                  {
                    "type": "file",
                    "id": "comunidades/formacion/facultades/ciencias-matematicas-y-naturales/index.mdx",
                    "name": "index",
                    "slug": "comunidades/formacion/facultades/ciencias-matematicas-y-naturales/index",
                    "href": "/comunidades/formacion/facultades/ciencias-matematicas-y-naturales/index",
                    "children": []
                  }
                ]
              }
            ]
          },
          {
            "type": "file",
            "id": "comunidades/formacion/index.mdx",
            "name": "index",
            "slug": "comunidades/formacion/index",
            "href": "/comunidades/formacion/index",
            "children": []
          }
        ]
      },
      {
        "type": "folder",
        "id": "comunidades/gobierno",
        "name": "gobierno",
        "slug": "comunidades/gobierno",
        "children": [
          {
            "type": "folder",
            "id": "comunidades/gobierno/csu",
            "name": "csu",
            "slug": "comunidades/gobierno/csu",
            "children": [
              {
                "type": "file",
                "id": "comunidades/gobierno/csu/index.mdx",
                "name": "index",
                "slug": "comunidades/gobierno/csu/index",
                "href": "/comunidades/gobierno/csu/index",
                "children": []
              }
            ]
          },
          {
            "type": "folder",
            "id": "comunidades/gobierno/direcciones",
            "name": "direcciones",
            "slug": "comunidades/gobierno/direcciones",
            "children": [
              {
                "type": "folder",
                "id": "comunidades/gobierno/direcciones/administrativa",
                "name": "administrativa",
                "slug": "comunidades/gobierno/direcciones/administrativa",
                "children": [
                  {
                    "type": "file",
                    "id": "comunidades/gobierno/direcciones/administrativa/index.mdx",
                    "name": "index",
                    "slug": "comunidades/gobierno/direcciones/administrativa/index",
                    "href": "/comunidades/gobierno/direcciones/administrativa/index",
                    "children": []
                  }
                ]
              },
              {
                "type": "folder",
                "id": "comunidades/gobierno/direcciones/bienestar",
                "name": "bienestar",
                "slug": "comunidades/gobierno/direcciones/bienestar",
                "children": [
                  {
                    "type": "file",
                    "id": "comunidades/gobierno/direcciones/bienestar/index.mdx",
                    "name": "index",
                    "slug": "comunidades/gobierno/direcciones/bienestar/index",
                    "href": "/comunidades/gobierno/direcciones/bienestar/index",
                    "children": []
                  }
                ]
              },
              {
                "type": "folder",
                "id": "comunidades/gobierno/direcciones/planeacion",
                "name": "planeacion",
                "slug": "comunidades/gobierno/direcciones/planeacion",
                "children": [
                  {
                    "type": "file",
                    "id": "comunidades/gobierno/direcciones/planeacion/index.mdx",
                    "name": "index",
                    "slug": "comunidades/gobierno/direcciones/planeacion/index",
                    "href": "/comunidades/gobierno/direcciones/planeacion/index",
                    "children": []
                  }
                ]
              }
            ]
          },
          {
            "type": "folder",
            "id": "comunidades/gobierno/rectoria",
            "name": "rectoria",
            "slug": "comunidades/gobierno/rectoria",
            "children": [
              {
                "type": "file",
                "id": "comunidades/gobierno/rectoria/index.mdx",
                "name": "index",
                "slug": "comunidades/gobierno/rectoria/index",
                "href": "/comunidades/gobierno/rectoria/index",
                "children": []
              }
            ]
          },
          {
            "type": "file",
            "id": "comunidades/gobierno/index.mdx",
            "name": "index",
            "slug": "comunidades/gobierno/index",
            "href": "/comunidades/gobierno/index",
            "children": []
          }
        ]
      },
      {
        "type": "folder",
        "id": "comunidades/investigacion",
        "name": "investigacion",
        "slug": "comunidades/investigacion",
        "children": [
          {
            "type": "folder",
            "id": "comunidades/investigacion/institutos",
            "name": "institutos",
            "slug": "comunidades/investigacion/institutos",
            "children": [
              {
                "type": "folder",
                "id": "comunidades/investigacion/institutos/ieie",
                "name": "ieie",
                "slug": "comunidades/investigacion/institutos/ieie",
                "children": [
                  {
                    "type": "file",
                    "id": "comunidades/investigacion/institutos/ieie/index.mdx",
                    "name": "index",
                    "slug": "comunidades/investigacion/institutos/ieie/index",
                    "href": "/comunidades/investigacion/institutos/ieie/index",
                    "children": []
                  }
                ]
              },
              {
                "type": "folder",
                "id": "comunidades/investigacion/institutos/ijplus",
                "name": "ijplus",
                "slug": "comunidades/investigacion/institutos/ijplus",
                "children": [
                  {
                    "type": "file",
                    "id": "comunidades/investigacion/institutos/ijplus/index.mdx",
                    "name": "index",
                    "slug": "comunidades/investigacion/institutos/ijplus/index",
                    "href": "/comunidades/investigacion/institutos/ijplus/index",
                    "children": []
                  }
                ]
              },
              {
                "type": "folder",
                "id": "comunidades/investigacion/institutos/ipazud",
                "name": "ipazud",
                "slug": "comunidades/investigacion/institutos/ipazud",
                "children": [
                  {
                    "type": "file",
                    "id": "comunidades/investigacion/institutos/ipazud/index.mdx",
                    "name": "index",
                    "slug": "comunidades/investigacion/institutos/ipazud/index",
                    "href": "/comunidades/investigacion/institutos/ipazud/index",
                    "children": []
                  }
                ]
              }
            ]
          },
          {
            "type": "file",
            "id": "comunidades/investigacion/index.mdx",
            "name": "index",
            "slug": "comunidades/investigacion/index",
            "href": "/comunidades/investigacion/index",
            "children": []
          }
        ]
      },
      {
        "type": "file",
        "id": "comunidades/index.mdx",
        "name": "index",
        "slug": "comunidades/index",
        "href": "/comunidades/index",
        "children": []
      }
    ]
  },
  {
    "type": "folder",
    "id": "feed",
    "name": "feed",
    "slug": "feed",
    "children": [
      {
        "type": "file",
        "id": "feed/news-2026-03-csu-cronograma-reforma.md",
        "name": "news-2026-03-csu-cronograma-reforma",
        "slug": "feed/news-2026-03-csu-cronograma-reforma",
        "href": "/feed/news-2026-03-csu-cronograma-reforma",
        "children": []
      },
      {
        "type": "file",
        "id": "feed/news-2026-04-instagram-reforma-vinculante.md",
        "name": "news-2026-04-instagram-reforma-vinculante",
        "slug": "feed/news-2026-04-instagram-reforma-vinculante",
        "href": "/feed/news-2026-04-instagram-reforma-vinculante",
        "children": []
      },
      {
        "type": "file",
        "id": "feed/news-2026-04-vr-formacion-acuerdo-creditos.md",
        "name": "news-2026-04-vr-formacion-acuerdo-creditos",
        "slug": "feed/news-2026-04-vr-formacion-acuerdo-creditos",
        "href": "/feed/news-2026-04-vr-formacion-acuerdo-creditos",
        "children": []
      }
    ]
  },
  {
    "type": "folder",
    "id": "glosario",
    "name": "glosario",
    "slug": "glosario",
    "children": [
      {
        "type": "file",
        "id": "glosario/con-10-principios-generales.md",
        "name": "con-10-principios-generales",
        "slug": "glosario/con-10-principios-generales",
        "href": "/glosario/con-10-principios-generales",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-abet-acreditacion.md",
        "name": "con-abet-acreditacion",
        "slug": "glosario/con-abet-acreditacion",
        "href": "/glosario/con-abet-acreditacion",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-acu-004-25.md",
        "name": "con-acu-004-25",
        "slug": "glosario/con-acu-004-25",
        "href": "/glosario/con-acu-004-25",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-acuerdo-csu-009-2018-ped.md",
        "name": "con-acuerdo-csu-009-2018-ped",
        "slug": "glosario/con-acuerdo-csu-009-2018-ped",
        "href": "/glosario/con-acuerdo-csu-009-2018-ped",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-acuerdo-csu-011-2018-pui.md",
        "name": "con-acuerdo-csu-011-2018-pui",
        "slug": "glosario/con-acuerdo-csu-011-2018-pui",
        "href": "/glosario/con-acuerdo-csu-011-2018-pui",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-anti-patron-departamentalizacion.md",
        "name": "con-anti-patron-departamentalizacion",
        "slug": "glosario/con-anti-patron-departamentalizacion",
        "href": "/glosario/con-anti-patron-departamentalizacion",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-arcu-sur.md",
        "name": "con-arcu-sur",
        "slug": "glosario/con-arcu-sur",
        "href": "/glosario/con-arcu-sur",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-area-formacion.md",
        "name": "con-area-formacion",
        "slug": "glosario/con-area-formacion",
        "href": "/glosario/con-area-formacion",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-asamblea-universitaria.md",
        "name": "con-asamblea-universitaria",
        "slug": "glosario/con-asamblea-universitaria",
        "href": "/glosario/con-asamblea-universitaria",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-autonomia-funcional-instrumental.md",
        "name": "con-autonomia-funcional-instrumental",
        "slug": "glosario/con-autonomia-funcional-instrumental",
        "href": "/glosario/con-autonomia-funcional-instrumental",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-autonomia-positiva.md",
        "name": "con-autonomia-positiva",
        "slug": "glosario/con-autonomia-positiva",
        "href": "/glosario/con-autonomia-positiva",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-bmk-001-21-ies.md",
        "name": "con-bmk-001-21-ies",
        "slug": "glosario/con-bmk-001-21-ies",
        "href": "/glosario/con-bmk-001-21-ies",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-bmk-002-cca-11-ies.md",
        "name": "con-bmk-002-cca-11-ies",
        "slug": "glosario/con-bmk-002-cca-11-ies",
        "href": "/glosario/con-bmk-002-cca-11-ies",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-boyer-healey-research-teaching.md",
        "name": "con-boyer-healey-research-teaching",
        "slug": "glosario/con-boyer-healey-research-teaching",
        "href": "/glosario/con-boyer-healey-research-teaching",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-bpa-001-21-buenas-practicas.md",
        "name": "con-bpa-001-21-buenas-practicas",
        "slug": "glosario/con-bpa-001-21-buenas-practicas",
        "href": "/glosario/con-bpa-001-21-buenas-practicas",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-bpa-e01-tto-transferencia.md",
        "name": "con-bpa-e01-tto-transferencia",
        "slug": "glosario/con-bpa-e01-tto-transferencia",
        "href": "/glosario/con-bpa-e01-tto-transferencia",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-bpa-e03-educacion-continua.md",
        "name": "con-bpa-e03-educacion-continua",
        "slug": "glosario/con-bpa-e03-educacion-continua",
        "href": "/glosario/con-bpa-e03-educacion-continua",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-bpa-e04-articulacion-media.md",
        "name": "con-bpa-e04-articulacion-media",
        "slug": "glosario/con-bpa-e04-articulacion-media",
        "href": "/glosario/con-bpa-e04-articulacion-media",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-bpa-f01-core-curriculum.md",
        "name": "con-bpa-f01-core-curriculum",
        "slug": "glosario/con-bpa-f01-core-curriculum",
        "href": "/glosario/con-bpa-f01-core-curriculum",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-bpa-f02-pbl-proyectos.md",
        "name": "con-bpa-f02-pbl-proyectos",
        "slug": "glosario/con-bpa-f02-pbl-proyectos",
        "href": "/glosario/con-bpa-f02-pbl-proyectos",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-bpa-f03-flexibilidad-curricular.md",
        "name": "con-bpa-f03-flexibilidad-curricular",
        "slug": "glosario/con-bpa-f03-flexibilidad-curricular",
        "href": "/glosario/con-bpa-f03-flexibilidad-curricular",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-bpa-f04-coop-practicas.md",
        "name": "con-bpa-f04-coop-practicas",
        "slug": "glosario/con-bpa-f04-coop-practicas",
        "href": "/glosario/con-bpa-f04-coop-practicas",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-bpa-f05-ciclos-propedeuticos.md",
        "name": "con-bpa-f05-ciclos-propedeuticos",
        "slug": "glosario/con-bpa-f05-ciclos-propedeuticos",
        "href": "/glosario/con-bpa-f05-ciclos-propedeuticos",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-bpa-i01-urop-investigacion-pregrado.md",
        "name": "con-bpa-i01-urop-investigacion-pregrado",
        "slug": "glosario/con-bpa-i01-urop-investigacion-pregrado",
        "href": "/glosario/con-bpa-i01-urop-investigacion-pregrado",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-bpa-i02-pi-inventor-friendly.md",
        "name": "con-bpa-i02-pi-inventor-friendly",
        "slug": "glosario/con-bpa-i02-pi-inventor-friendly",
        "href": "/glosario/con-bpa-i02-pi-inventor-friendly",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-bpa-i03-cris-hub.md",
        "name": "con-bpa-i03-cris-hub",
        "slug": "glosario/con-bpa-i03-cris-hub",
        "href": "/glosario/con-bpa-i03-cris-hub",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-bpa-i04-open-science.md",
        "name": "con-bpa-i04-open-science",
        "slug": "glosario/con-bpa-i04-open-science",
        "href": "/glosario/con-bpa-i04-open-science",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-bpa-i05-ecosistema-spinoffs.md",
        "name": "con-bpa-i05-ecosistema-spinoffs",
        "slug": "glosario/con-bpa-i05-ecosistema-spinoffs",
        "href": "/glosario/con-bpa-i05-ecosistema-spinoffs",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-bpa-int01-mision-operacionalizada.md",
        "name": "con-bpa-int01-mision-operacionalizada",
        "slug": "glosario/con-bpa-int01-mision-operacionalizada",
        "href": "/glosario/con-bpa-int01-mision-operacionalizada",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-bpa-int02-creditos-investigacion-extension.md",
        "name": "con-bpa-int02-creditos-investigacion-extension",
        "slug": "glosario/con-bpa-int02-creditos-investigacion-extension",
        "href": "/glosario/con-bpa-int02-creditos-investigacion-extension",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-bpa-int03-clr-learner-record.md",
        "name": "con-bpa-int03-clr-learner-record",
        "slug": "glosario/con-bpa-int03-clr-learner-record",
        "href": "/glosario/con-bpa-int03-clr-learner-record",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-bpa-int04-caba-design-factory.md",
        "name": "con-bpa-int04-caba-design-factory",
        "slug": "glosario/con-bpa-int04-caba-design-factory",
        "href": "/glosario/con-bpa-int04-caba-design-factory",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-bpa-int05-racionalizacion-oferta.md",
        "name": "con-bpa-int05-racionalizacion-oferta",
        "slug": "glosario/con-bpa-int05-racionalizacion-oferta",
        "href": "/glosario/con-bpa-int05-racionalizacion-oferta",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-bpa-int06-retencion-engagement.md",
        "name": "con-bpa-int06-retencion-engagement",
        "slug": "glosario/con-bpa-int06-retencion-engagement",
        "href": "/glosario/con-bpa-int06-retencion-engagement",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-bpa-int07-extension-productiva.md",
        "name": "con-bpa-int07-extension-productiva",
        "slug": "glosario/con-bpa-int07-extension-productiva",
        "href": "/glosario/con-bpa-int07-extension-productiva",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-bsc-s.md",
        "name": "con-bsc-s",
        "slug": "glosario/con-bsc-s",
        "href": "/glosario/con-bsc-s",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-buen-vivir.md",
        "name": "con-buen-vivir",
        "slug": "glosario/con-buen-vivir",
        "href": "/glosario/con-buen-vivir",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-caba.md",
        "name": "con-caba",
        "slug": "glosario/con-caba",
        "href": "/glosario/con-caba",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-cacad-consejo-academico.md",
        "name": "con-cacad-consejo-academico",
        "slug": "glosario/con-cacad-consejo-academico",
        "href": "/glosario/con-cacad-consejo-academico",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-cadena-normativa-multinivel.md",
        "name": "con-cadena-normativa-multinivel",
        "slug": "glosario/con-cadena-normativa-multinivel",
        "href": "/glosario/con-cadena-normativa-multinivel",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-campo-conocimiento-saber.md",
        "name": "con-campo-conocimiento-saber",
        "slug": "glosario/con-campo-conocimiento-saber",
        "href": "/glosario/con-campo-conocimiento-saber",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-cca.md",
        "name": "con-cca",
        "slug": "glosario/con-cca",
        "href": "/glosario/con-cca",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-ccp-clasificacion-presupuestal.md",
        "name": "con-ccp-clasificacion-presupuestal",
        "slug": "glosario/con-ccp-clasificacion-presupuestal",
        "href": "/glosario/con-ccp-clasificacion-presupuestal",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-ccr-capacity-cost-rate.md",
        "name": "con-ccr-capacity-cost-rate",
        "slug": "glosario/con-ccr-capacity-cost-rate",
        "href": "/glosario/con-ccr-capacity-cost-rate",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-cdio-syllabus.md",
        "name": "con-cdio-syllabus",
        "slug": "glosario/con-cdio-syllabus",
        "href": "/glosario/con-cdio-syllabus",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-centro.md",
        "name": "con-centro",
        "slug": "glosario/con-centro",
        "href": "/glosario/con-centro",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-cidc.md",
        "name": "con-cidc",
        "slug": "glosario/con-cidc",
        "href": "/glosario/con-cidc",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-cinco-misiones-piiom.md",
        "name": "con-cinco-misiones-piiom",
        "slug": "glosario/con-cinco-misiones-piiom",
        "href": "/glosario/con-cinco-misiones-piiom",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-cinco-vias-clark.md",
        "name": "con-cinco-vias-clark",
        "slug": "glosario/con-cinco-vias-clark",
        "href": "/glosario/con-cinco-vias-clark",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-claustro-escuelas.md",
        "name": "con-claustro-escuelas",
        "slug": "glosario/con-claustro-escuelas",
        "href": "/glosario/con-claustro-escuelas",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-claustro-general-docente.md",
        "name": "con-claustro-general-docente",
        "slug": "glosario/con-claustro-general-docente",
        "href": "/glosario/con-claustro-general-docente",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-cognia-deprecated.md",
        "name": "con-cognia-deprecated",
        "slug": "glosario/con-cognia-deprecated",
        "href": "/glosario/con-cognia-deprecated",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-comision-implementacion-art-100.md",
        "name": "con-comision-implementacion-art-100",
        "slug": "glosario/con-comision-implementacion-art-100",
        "href": "/glosario/con-comision-implementacion-art-100",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-comunidad-universitaria.md",
        "name": "con-comunidad-universitaria",
        "slug": "glosario/con-comunidad-universitaria",
        "href": "/glosario/con-comunidad-universitaria",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-conpes-3934.md",
        "name": "con-conpes-3934",
        "slug": "glosario/con-conpes-3934",
        "href": "/glosario/con-conpes-3934",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-conpes-4069.md",
        "name": "con-conpes-4069",
        "slug": "glosario/con-conpes-4069",
        "href": "/glosario/con-conpes-4069",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-consejo-bienestar-buen-vivir.md",
        "name": "con-consejo-bienestar-buen-vivir",
        "slug": "glosario/con-consejo-bienestar-buen-vivir",
        "href": "/glosario/con-consejo-bienestar-buen-vivir",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-consejo-centro.md",
        "name": "con-consejo-centro",
        "slug": "glosario/con-consejo-centro",
        "href": "/glosario/con-consejo-centro",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-consejo-electoral.md",
        "name": "con-consejo-electoral",
        "slug": "glosario/con-consejo-electoral",
        "href": "/glosario/con-consejo-electoral",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-consejo-escuela.md",
        "name": "con-consejo-escuela",
        "slug": "glosario/con-consejo-escuela",
        "href": "/glosario/con-consejo-escuela",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-consejo-estudiantil-universitario.md",
        "name": "con-consejo-estudiantil-universitario",
        "slug": "glosario/con-consejo-estudiantil-universitario",
        "href": "/glosario/con-consejo-estudiantil-universitario",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-consejo-facultad.md",
        "name": "con-consejo-facultad",
        "slug": "glosario/con-consejo-facultad",
        "href": "/glosario/con-consejo-facultad",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-consejo-gestion-administrativa.md",
        "name": "con-consejo-gestion-administrativa",
        "slug": "glosario/con-consejo-gestion-administrativa",
        "href": "/glosario/con-consejo-gestion-administrativa",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-consejo-instituto.md",
        "name": "con-consejo-instituto",
        "slug": "glosario/con-consejo-instituto",
        "href": "/glosario/con-consejo-instituto",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-consejo-participacion-universitaria.md",
        "name": "con-consejo-participacion-universitaria",
        "slug": "glosario/con-consejo-participacion-universitaria",
        "href": "/glosario/con-consejo-participacion-universitaria",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-constitucion-1991-art-69.md",
        "name": "con-constitucion-1991-art-69",
        "slug": "glosario/con-constitucion-1991-art-69",
        "href": "/glosario/con-constitucion-1991-art-69",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-cops-wenger.md",
        "name": "con-cops-wenger",
        "slug": "glosario/con-cops-wenger",
        "href": "/glosario/con-cops-wenger",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-core-competencies-prahalad-hamel.md",
        "name": "con-core-competencies-prahalad-hamel",
        "slug": "glosario/con-core-competencies-prahalad-hamel",
        "href": "/glosario/con-core-competencies-prahalad-hamel",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-credito-academico.md",
        "name": "con-credito-academico",
        "slug": "glosario/con-credito-academico",
        "href": "/glosario/con-credito-academico",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-crisp-dm.md",
        "name": "con-crisp-dm",
        "slug": "glosario/con-crisp-dm",
        "href": "/glosario/con-crisp-dm",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-csu-consejo-superior-universitario.md",
        "name": "con-csu-consejo-superior-universitario",
        "slug": "glosario/con-csu-consejo-superior-universitario",
        "href": "/glosario/con-csu-consejo-superior-universitario",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-cuadrante-pasteur-stokes.md",
        "name": "con-cuadrante-pasteur-stokes",
        "slug": "glosario/con-cuadrante-pasteur-stokes",
        "href": "/glosario/con-cuadrante-pasteur-stokes",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-culture-lag.md",
        "name": "con-culture-lag",
        "slug": "glosario/con-culture-lag",
        "href": "/glosario/con-culture-lag",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-deber-normativo.md",
        "name": "con-deber-normativo",
        "slug": "glosario/con-deber-normativo",
        "href": "/glosario/con-deber-normativo",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-decanatura.md",
        "name": "con-decanatura",
        "slug": "glosario/con-decanatura",
        "href": "/glosario/con-decanatura",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-decreto-1330-2019.md",
        "name": "con-decreto-1330-2019",
        "slug": "glosario/con-decreto-1330-2019",
        "href": "/glosario/con-decreto-1330-2019",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-decreto-1421-2017.md",
        "name": "con-decreto-1421-2017",
        "slug": "glosario/con-decreto-1421-2017",
        "href": "/glosario/con-decreto-1421-2017",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-direccion-bienestar-buen-vivir.md",
        "name": "con-direccion-bienestar-buen-vivir",
        "slug": "glosario/con-direccion-bienestar-buen-vivir",
        "href": "/glosario/con-direccion-bienestar-buen-vivir",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-direccion-centro.md",
        "name": "con-direccion-centro",
        "slug": "glosario/con-direccion-centro",
        "href": "/glosario/con-direccion-centro",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-direccion-gestion-estrategica-planeacion.md",
        "name": "con-direccion-gestion-estrategica-planeacion",
        "slug": "glosario/con-direccion-gestion-estrategica-planeacion",
        "href": "/glosario/con-direccion-gestion-estrategica-planeacion",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-direccion-instituto.md",
        "name": "con-direccion-instituto",
        "slug": "glosario/con-direccion-instituto",
        "href": "/glosario/con-direccion-instituto",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-director-escuela.md",
        "name": "con-director-escuela",
        "slug": "glosario/con-director-escuela",
        "href": "/glosario/con-director-escuela",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-dublin-descriptors-bologna.md",
        "name": "con-dublin-descriptors-bologna",
        "slug": "glosario/con-dublin-descriptors-bologna",
        "href": "/glosario/con-dublin-descriptors-bologna",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-ecuacion-ccr-tdabc.md",
        "name": "con-ecuacion-ccr-tdabc",
        "slug": "glosario/con-ecuacion-ccr-tdabc",
        "href": "/glosario/con-ecuacion-ccr-tdabc",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-ecuacion-iuca.md",
        "name": "con-ecuacion-iuca",
        "slug": "glosario/con-ecuacion-iuca",
        "href": "/glosario/con-ecuacion-iuca",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-ecuacion-ivc.md",
        "name": "con-ecuacion-ivc",
        "slug": "glosario/con-ecuacion-ivc",
        "href": "/glosario/con-ecuacion-ivc",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-ecuacion-ivo.md",
        "name": "con-ecuacion-ivo",
        "slug": "glosario/con-ecuacion-ivo",
        "href": "/glosario/con-ecuacion-ivo",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-ecuacion-smmlv-pais.md",
        "name": "con-ecuacion-smmlv-pais",
        "slug": "glosario/con-ecuacion-smmlv-pais",
        "href": "/glosario/con-ecuacion-smmlv-pais",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-ecuacion-time-equation-tdabc.md",
        "name": "con-ecuacion-time-equation-tdabc",
        "slug": "glosario/con-ecuacion-time-equation-tdabc",
        "href": "/glosario/con-ecuacion-time-equation-tdabc",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-escuela.md",
        "name": "con-escuela",
        "slug": "glosario/con-escuela",
        "href": "/glosario/con-escuela",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-escuela-generica-udfjc.md",
        "name": "con-escuela-generica-udfjc",
        "slug": "glosario/con-escuela-generica-udfjc",
        "href": "/glosario/con-escuela-generica-udfjc",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-estructura-administrativa-soporte.md",
        "name": "con-estructura-administrativa-soporte",
        "slug": "glosario/con-estructura-administrativa-soporte",
        "href": "/glosario/con-estructura-administrativa-soporte",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-eur-ace.md",
        "name": "con-eur-ace",
        "slug": "glosario/con-eur-ace",
        "href": "/glosario/con-eur-ace",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-facultad.md",
        "name": "con-facultad",
        "slug": "glosario/con-facultad",
        "href": "/glosario/con-facultad",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-frame-1.md",
        "name": "con-frame-1",
        "slug": "glosario/con-frame-1",
        "href": "/glosario/con-frame-1",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-frame-2.md",
        "name": "con-frame-2",
        "slug": "glosario/con-frame-2",
        "href": "/glosario/con-frame-2",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-frame-3.md",
        "name": "con-frame-3",
        "slug": "glosario/con-frame-3",
        "href": "/glosario/con-frame-3",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-frame-men-kdmo.md",
        "name": "con-frame-men-kdmo",
        "slug": "glosario/con-frame-men-kdmo",
        "href": "/glosario/con-frame-men-kdmo",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-framework-86-indicadores-s0-s5.md",
        "name": "con-framework-86-indicadores-s0-s5",
        "slug": "glosario/con-framework-86-indicadores-s0-s5",
        "href": "/glosario/con-framework-86-indicadores-s0-s5",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-funciones-misionales.md",
        "name": "con-funciones-misionales",
        "slug": "glosario/con-funciones-misionales",
        "href": "/glosario/con-funciones-misionales",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-gerencia-administrativa-financiera.md",
        "name": "con-gerencia-administrativa-financiera",
        "slug": "glosario/con-gerencia-administrativa-financiera",
        "href": "/glosario/con-gerencia-administrativa-financiera",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-iniciativas-i0-i4.md",
        "name": "con-iniciativas-i0-i4",
        "slug": "glosario/con-iniciativas-i0-i4",
        "href": "/glosario/con-iniciativas-i0-i4",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-instituto.md",
        "name": "con-instituto",
        "slug": "glosario/con-instituto",
        "href": "/glosario/con-instituto",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-iso-21001.md",
        "name": "con-iso-21001",
        "slug": "glosario/con-iso-21001",
        "href": "/glosario/con-iso-21001",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-iso-9001.md",
        "name": "con-iso-9001",
        "slug": "glosario/con-iso-9001",
        "href": "/glosario/con-iso-9001",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-iuca-ivc-ivo-indices.md",
        "name": "con-iuca-ivc-ivo-indices",
        "slug": "glosario/con-iuca-ivc-ivo-indices",
        "href": "/glosario/con-iuca-ivc-ivo-indices",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-jtbd-christensen.md",
        "name": "con-jtbd-christensen",
        "slug": "glosario/con-jtbd-christensen",
        "href": "/glosario/con-jtbd-christensen",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-ley-1618-2013.md",
        "name": "con-ley-1618-2013",
        "slug": "glosario/con-ley-1618-2013",
        "href": "/glosario/con-ley-1618-2013",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-ley-30-1992-art-6.md",
        "name": "con-ley-30-1992-art-6",
        "slug": "glosario/con-ley-30-1992-art-6",
        "href": "/glosario/con-ley-30-1992-art-6",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-living-labs-f4-integracion.md",
        "name": "con-living-labs-f4-integracion",
        "slug": "glosario/con-living-labs-f4-integracion",
        "href": "/glosario/con-living-labs-f4-integracion",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-marco-p1-impacto-misional.md",
        "name": "con-marco-p1-impacto-misional",
        "slug": "glosario/con-marco-p1-impacto-misional",
        "href": "/glosario/con-marco-p1-impacto-misional",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-mcu-2020.md",
        "name": "con-mcu-2020",
        "slug": "glosario/con-mcu-2020",
        "href": "/glosario/con-mcu-2020",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-mipg-funcion-publica.md",
        "name": "con-mipg-funcion-publica",
        "slug": "glosario/con-mipg-funcion-publica",
        "href": "/glosario/con-mipg-funcion-publica",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-mision-institucional-udfjc.md",
        "name": "con-mision-institucional-udfjc",
        "slug": "glosario/con-mision-institucional-udfjc",
        "href": "/glosario/con-mision-institucional-udfjc",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-mision-sabios-2019.md",
        "name": "con-mision-sabios-2019",
        "slug": "glosario/con-mision-sabios-2019",
        "href": "/glosario/con-mision-sabios-2019",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-mit-urop.md",
        "name": "con-mit-urop",
        "slug": "glosario/con-mit-urop",
        "href": "/glosario/con-mit-urop",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-mlp-geels.md",
        "name": "con-mlp-geels",
        "slug": "glosario/con-mlp-geels",
        "href": "/glosario/con-mlp-geels",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-mode-1-2-3.md",
        "name": "con-mode-1-2-3",
        "slug": "glosario/con-mode-1-2-3",
        "href": "/glosario/con-mode-1-2-3",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-nicsp-marco-estado-resultados.md",
        "name": "con-nicsp-marco-estado-resultados",
        "slug": "glosario/con-nicsp-marco-estado-resultados",
        "href": "/glosario/con-nicsp-marco-estado-resultados",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-niveles-adopcion-l0-l4.md",
        "name": "con-niveles-adopcion-l0-l4",
        "slug": "glosario/con-niveles-adopcion-l0-l4",
        "href": "/glosario/con-niveles-adopcion-l0-l4",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-odi-ulwick.md",
        "name": "con-odi-ulwick",
        "slug": "glosario/con-odi-ulwick",
        "href": "/glosario/con-odi-ulwick",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-ods-agenda-2030.md",
        "name": "con-ods-agenda-2030",
        "slug": "glosario/con-ods-agenda-2030",
        "href": "/glosario/con-ods-agenda-2030",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-oecd-learning-compass-2030.md",
        "name": "con-oecd-learning-compass-2030",
        "slug": "glosario/con-oecd-learning-compass-2030",
        "href": "/glosario/con-oecd-learning-compass-2030",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-oficina-asesora-planeacion.md",
        "name": "con-oficina-asesora-planeacion",
        "slug": "glosario/con-oficina-asesora-planeacion",
        "href": "/glosario/con-oficina-asesora-planeacion",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-oficina-comunicaciones.md",
        "name": "con-oficina-comunicaciones",
        "slug": "glosario/con-oficina-comunicaciones",
        "href": "/glosario/con-oficina-comunicaciones",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-oficina-control-interno.md",
        "name": "con-oficina-control-interno",
        "slug": "glosario/con-oficina-control-interno",
        "href": "/glosario/con-oficina-control-interno",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-oficina-egresados.md",
        "name": "con-oficina-egresados",
        "slug": "glosario/con-oficina-egresados",
        "href": "/glosario/con-oficina-egresados",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-ole-observatorio-laboral.md",
        "name": "con-ole-observatorio-laboral",
        "slug": "glosario/con-ole-observatorio-laboral",
        "href": "/glosario/con-ole-observatorio-laboral",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-omt.md",
        "name": "con-omt",
        "slug": "glosario/con-omt",
        "href": "/glosario/con-omt",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-periodo-transicion.md",
        "name": "con-periodo-transicion",
        "slug": "glosario/con-periodo-transicion",
        "href": "/glosario/con-periodo-transicion",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-piiom.md",
        "name": "con-piiom",
        "slug": "glosario/con-piiom",
        "href": "/glosario/con-piiom",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-plan-implementacion.md",
        "name": "con-plan-implementacion",
        "slug": "glosario/con-plan-implementacion",
        "href": "/glosario/con-plan-implementacion",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-plataforma-comunitaria-9-modulos.md",
        "name": "con-plataforma-comunitaria-9-modulos",
        "slug": "glosario/con-plataforma-comunitaria-9-modulos",
        "href": "/glosario/con-plataforma-comunitaria-9-modulos",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-potestad-rectoral-transitoria.md",
        "name": "con-potestad-rectoral-transitoria",
        "slug": "glosario/con-potestad-rectoral-transitoria",
        "href": "/glosario/con-potestad-rectoral-transitoria",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-presupuesto-participativo.md",
        "name": "con-presupuesto-participativo",
        "slug": "glosario/con-presupuesto-participativo",
        "href": "/glosario/con-presupuesto-participativo",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-procesos-misionales-pm1-pm2-pm3.md",
        "name": "con-procesos-misionales-pm1-pm2-pm3",
        "slug": "glosario/con-procesos-misionales-pm1-pm2-pm3",
        "href": "/glosario/con-procesos-misionales-pm1-pm2-pm3",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-programa-academico.md",
        "name": "con-programa-academico",
        "slug": "glosario/con-programa-academico",
        "href": "/glosario/con-programa-academico",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-programa-pregrado-posgrado.md",
        "name": "con-programa-pregrado-posgrado",
        "slug": "glosario/con-programa-pregrado-posgrado",
        "href": "/glosario/con-programa-pregrado-posgrado",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-quintuple-helix.md",
        "name": "con-quintuple-helix",
        "slug": "glosario/con-quintuple-helix",
        "href": "/glosario/con-quintuple-helix",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-rbm-gac.md",
        "name": "con-rbm-gac",
        "slug": "glosario/con-rbm-gac",
        "href": "/glosario/con-rbm-gac",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-re-ontologizacion.md",
        "name": "con-re-ontologizacion",
        "slug": "glosario/con-re-ontologizacion",
        "href": "/glosario/con-re-ontologizacion",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-rectoria.md",
        "name": "con-rectoria",
        "slug": "glosario/con-rectoria",
        "href": "/glosario/con-rectoria",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-resolucion-rectoria-207-2016-sigud.md",
        "name": "con-resolucion-rectoria-207-2016-sigud",
        "slug": "glosario/con-resolucion-rectoria-207-2016-sigud",
        "href": "/glosario/con-resolucion-rectoria-207-2016-sigud",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-resultados-emergentes-e1-e3.md",
        "name": "con-resultados-emergentes-e1-e3",
        "slug": "glosario/con-resultados-emergentes-e1-e3",
        "href": "/glosario/con-resultados-emergentes-e1-e3",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-retroalimentaciones-r1-r6.md",
        "name": "con-retroalimentaciones-r1-r6",
        "slug": "glosario/con-retroalimentaciones-r1-r6",
        "href": "/glosario/con-retroalimentaciones-r1-r6",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-riesgos-rt1-rt6.md",
        "name": "con-riesgos-rt1-rt6",
        "slug": "glosario/con-riesgos-rt1-rt6",
        "href": "/glosario/con-riesgos-rt1-rt6",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-salto-cuantico-sub-n1-n4.md",
        "name": "con-salto-cuantico-sub-n1-n4",
        "slug": "glosario/con-salto-cuantico-sub-n1-n4",
        "href": "/glosario/con-salto-cuantico-sub-n1-n4",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-seci-ba-nonaka.md",
        "name": "con-seci-ba-nonaka",
        "slug": "glosario/con-seci-ba-nonaka",
        "href": "/glosario/con-seci-ba-nonaka",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-secretaria-academica-escuela.md",
        "name": "con-secretaria-academica-escuela",
        "slug": "glosario/con-secretaria-academica-escuela",
        "href": "/glosario/con-secretaria-academica-escuela",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-secretaria-academica-facultad.md",
        "name": "con-secretaria-academica-facultad",
        "slug": "glosario/con-secretaria-academica-facultad",
        "href": "/glosario/con-secretaria-academica-facultad",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-secretaria-general-sisgral.md",
        "name": "con-secretaria-general-sisgral",
        "slug": "glosario/con-secretaria-general-sisgral",
        "href": "/glosario/con-secretaria-general-sisgral",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-segunda-revolucion-academica-etzkowitz.md",
        "name": "con-segunda-revolucion-academica-etzkowitz",
        "slug": "glosario/con-segunda-revolucion-academica-etzkowitz",
        "href": "/glosario/con-segunda-revolucion-academica-etzkowitz",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-seis-dimensiones-markard.md",
        "name": "con-seis-dimensiones-markard",
        "slug": "glosario/con-seis-dimensiones-markard",
        "href": "/glosario/con-seis-dimensiones-markard",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-seis-roles-jtbd-comunidad-udfjc.md",
        "name": "con-seis-roles-jtbd-comunidad-udfjc",
        "slug": "glosario/con-seis-roles-jtbd-comunidad-udfjc",
        "href": "/glosario/con-seis-roles-jtbd-comunidad-udfjc",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-sigud-daruma-procesos-phva.md",
        "name": "con-sigud-daruma-procesos-phva",
        "slug": "glosario/con-sigud-daruma-procesos-phva",
        "href": "/glosario/con-sigud-daruma-procesos-phva",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-sistema-bienestar-buen-vivir.md",
        "name": "con-sistema-bienestar-buen-vivir",
        "slug": "glosario/con-sistema-bienestar-buen-vivir",
        "href": "/glosario/con-sistema-bienestar-buen-vivir",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-smmlv-pais-2026.md",
        "name": "con-smmlv-pais-2026",
        "slug": "glosario/con-smmlv-pais-2026",
        "href": "/glosario/con-smmlv-pais-2026",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-sncti.md",
        "name": "con-sncti",
        "slug": "glosario/con-sncti",
        "href": "/glosario/con-sncti",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-snies-dataset-men.md",
        "name": "con-snies-dataset-men",
        "slug": "glosario/con-snies-dataset-men",
        "href": "/glosario/con-snies-dataset-men",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-soberania-cognitiva.md",
        "name": "con-soberania-cognitiva",
        "slug": "glosario/con-soberania-cognitiva",
        "href": "/glosario/con-soberania-cognitiva",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-spadies-snies-dataset-men.md",
        "name": "con-spadies-snies-dataset-men",
        "slug": "glosario/con-spadies-snies-dataset-men",
        "href": "/glosario/con-spadies-snies-dataset-men",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-stack-certificacion-open-badges.md",
        "name": "con-stack-certificacion-open-badges",
        "slug": "glosario/con-stack-certificacion-open-badges",
        "href": "/glosario/con-stack-certificacion-open-badges",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-subsistema-gestion-estrategica.md",
        "name": "con-subsistema-gestion-estrategica",
        "slug": "glosario/con-subsistema-gestion-estrategica",
        "href": "/glosario/con-subsistema-gestion-estrategica",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-subsistema-gestion-normativa-documental.md",
        "name": "con-subsistema-gestion-normativa-documental",
        "slug": "glosario/con-subsistema-gestion-normativa-documental",
        "href": "/glosario/con-subsistema-gestion-normativa-documental",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-subsistema-talento-financiero-infraestructura.md",
        "name": "con-subsistema-talento-financiero-infraestructura",
        "slug": "glosario/con-subsistema-talento-financiero-infraestructura",
        "href": "/glosario/con-subsistema-talento-financiero-infraestructura",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-taxonomia-sub-n1-n4.md",
        "name": "con-taxonomia-sub-n1-n4",
        "slug": "glosario/con-taxonomia-sub-n1-n4",
        "href": "/glosario/con-taxonomia-sub-n1-n4",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-tdabc-lite-12-time-equations.md",
        "name": "con-tdabc-lite-12-time-equations",
        "slug": "glosario/con-tdabc-lite-12-time-equations",
        "href": "/glosario/con-tdabc-lite-12-time-equations",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-tercera-mision-compagnucci.md",
        "name": "con-tercera-mision-compagnucci",
        "slug": "glosario/con-tercera-mision-compagnucci",
        "href": "/glosario/con-tercera-mision-compagnucci",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-triple-helix-etzkowitz.md",
        "name": "con-triple-helix-etzkowitz",
        "slug": "glosario/con-triple-helix-etzkowitz",
        "href": "/glosario/con-triple-helix-etzkowitz",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-tuning-america-latina.md",
        "name": "con-tuning-america-latina",
        "slug": "glosario/con-tuning-america-latina",
        "href": "/glosario/con-tuning-america-latina",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-udfjc-ente-autonomo.md",
        "name": "con-udfjc-ente-autonomo",
        "slug": "glosario/con-udfjc-ente-autonomo",
        "href": "/glosario/con-udfjc-ente-autonomo",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-udl-3.md",
        "name": "con-udl-3",
        "slug": "glosario/con-udl-3",
        "href": "/glosario/con-udl-3",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-unesco-beyond-2024.md",
        "name": "con-unesco-beyond-2024",
        "slug": "glosario/con-unesco-beyond-2024",
        "href": "/glosario/con-unesco-beyond-2024",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-unesco-reimagining-2021.md",
        "name": "con-unesco-reimagining-2021",
        "slug": "glosario/con-unesco-reimagining-2021",
        "href": "/glosario/con-unesco-reimagining-2021",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-unidades-apoyo-curricular.md",
        "name": "con-unidades-apoyo-curricular",
        "slug": "glosario/con-unidades-apoyo-curricular",
        "href": "/glosario/con-unidades-apoyo-curricular",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-valores-culturales-v1-v5.md",
        "name": "con-valores-culturales-v1-v5",
        "slug": "glosario/con-valores-culturales-v1-v5",
        "href": "/glosario/con-valores-culturales-v1-v5",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-veeduria-universitaria.md",
        "name": "con-veeduria-universitaria",
        "slug": "glosario/con-veeduria-universitaria",
        "href": "/glosario/con-veeduria-universitaria",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-vicerrectoria-contextos-extension.md",
        "name": "con-vicerrectoria-contextos-extension",
        "slug": "glosario/con-vicerrectoria-contextos-extension",
        "href": "/glosario/con-vicerrectoria-contextos-extension",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-vicerrectoria-formacion.md",
        "name": "con-vicerrectoria-formacion",
        "slug": "glosario/con-vicerrectoria-formacion",
        "href": "/glosario/con-vicerrectoria-formacion",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-vicerrectoria-investigacion-creacion-innovacion.md",
        "name": "con-vicerrectoria-investigacion-creacion-innovacion",
        "slug": "glosario/con-vicerrectoria-investigacion-creacion-innovacion",
        "href": "/glosario/con-vicerrectoria-investigacion-creacion-innovacion",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-vigencia-transitoria-estatutos-previos.md",
        "name": "con-vigencia-transitoria-estatutos-previos",
        "slug": "glosario/con-vigencia-transitoria-estatutos-previos",
        "href": "/glosario/con-vigencia-transitoria-estatutos-previos",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-vsm-system-5.md",
        "name": "con-vsm-system-5",
        "slug": "glosario/con-vsm-system-5",
        "href": "/glosario/con-vsm-system-5",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/con-wenger-trayner-landscapes.md",
        "name": "con-wenger-trayner-landscapes",
        "slug": "glosario/con-wenger-trayner-landscapes",
        "href": "/glosario/con-wenger-trayner-landscapes",
        "children": []
      },
      {
        "type": "file",
        "id": "glosario/dash-glosario-universal.md",
        "name": "dash-glosario-universal",
        "slug": "glosario/dash-glosario-universal",
        "href": "/glosario/dash-glosario-universal",
        "children": []
      }
    ]
  }
];
